# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20170311_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='scan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scanner.Scan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 22, 31, 46, 987177)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 22, 31, 46, 987177)),
        ),
    ]
