# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_auto_20170311_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 22, 32, 12, 277363)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 22, 32, 12, 277363)),
        ),
    ]
